export enum ApiActions {
  REFRESH = 'REFRESH',
  RESET = 'RESET',
}

export enum ApiEvents {
  GET_START = 'GET_START',
  GET_SUCCESS = 'GET_SUCCESS',
  GET_ERROR = 'GET_ERROR',
  MODIFY_START = 'MODIFY_START',
  MODIFY_SUCCESS = 'MODIFY_SUCCESS',
  MODIFY_ERROR = 'MODIFY_ERROR',
}
