/** Reducer actions for the UI store */
export enum UIStoreActions {
  RESET = 'RESET',
  REHYDRATE = 'REHYDRATE',
  MODAL_OPEN = 'MODAL_OPEN',
  MODAL_UNLOAD = 'MODAL_UNLOAD',
  TAB_CHANGE = 'TAB_CHANGE',
  MULTISCREEN_TOGGLE = 'MULTISCREEN_TOGGLE',
}
