export enum ApiStatusActions {
  RESET = 'RESET',

  STATE_CHANGE = 'STATE_CHANGE',

  STATE_LOADING = 'STATE_LOADING',
  STATE_MODIFYING = 'STATE_MODIFYING',
  STATE_ERROR = 'STATE_ERROR',

  RESET_ERRORS = 'RESET_ERRORS',
  RESET_SUCCESS = 'RESET_SUCCESS',
  GET_COMPLETE = 'GET_COMPLETE',
  POST_COMPLETE = 'POST_COMPLETE',
  PUT_COMPLETE = 'PUT_COMPLETE',
  UPSERT_COMPLETE = 'UPSERT_COMPLETE',
  DELETE_COMPLETE = 'DELETE_COMPLETE',
}
