export enum ApiActions {
	RESET = 'RESET',
	STATE_CHANGE = 'STATE_CHANGE',
	RESET_ERRORS = 'RESET_ERRORS',
	RESET_SUCCESS = 'RESET_SUCCESS',
	GET_COMPLETE = 'GET_COMPLETE',
	POST_COMPLETE = 'POST_COMPLETE',
	PUT_COMPLETE = 'PUT_COMPLETE',
	DELETE_COMPLETE = 'DELETE_COMPLETE'
}
