// import { Datagrid } from '$libs';

export const columns: any[] = [
  {
    prop: 'name',
    label: 'Name',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'username',
    label: 'Username',
    columnType: 'string',
    width: 70,
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'email',
    label: 'Email',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'phone',
    label: 'Phone',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'website',
    label: 'Website',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'delete',
    label: 'Delete User',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
];
