name: Publish

on:
  push:
    branches:
      - 'dev/nx'

jobs:
  affected:
    name: Run Affected Build and Publish Targets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx nx affected --target build
      - name: Publish
        run: npx nx affected --target publish
